apiVersion: apps/v1
kind: Deployment
metadata:
    name: deployment
spec:
    selector:
        matchLabels:
            app: redis
    replicas: 1
    template:
        metadata:
            labels:
                app: redis
        spec:
            containers:
                - name: redis
                  image: redis
                  volumeMounts:
                    - name: vmfs-vmdk-storage
                      mountPath: /data/
                  securityContext:
                    readOnlyRootFilesystem: true
            volumes:
                - name: vmfs-vmdk-storage
                  vsphereVolume:
                    volumePath: "[Datastore] volumes/testdir"
                    fsType: ext4
